a: 0;
b: 1;
lambda: 2;
n: 5;

f(x) := cosh(x);

eigenfun(k) := if (k=0) then 1 else sqrt(2) * cos(%pi*k*x);
eigenval(k) := if (k=0) then 1 else 1 + (%pi*k)^2;

f_k(k) := integrate(f(x) * eigenfun(k), x, a, b);

series: sum(f_k(k) * eigenfun(k) / (eigenval(k) - lambda), k, 0, n-1)$

solution(y) := f(y) + lambda * at(series, x=y);

plot2d([solution(y)], [y, 0, 1], [nticks, 1], [adapt_depth, 1],
       [gnuplot_preamble, "set table \"series.mac.out\""]);
